### ISSUE TITLE
Missing explanation

### ISSUE THREAD

**Issue by KieranHons** [EntelectChallenge/2022-Arctica#8]
Hi, I was wondering if there was meant to be more explanation in this section?

https://github.com/EntelectChallenge/2022-Arctica/blob/master/game-engine/game-rules.md#day-night-cycle

Not sure if the following headers are released during the cycle, or if there are night restrictions (i.e. no gathering allowed)

**Comment by JeniquePeters** [comment]
Hi @KieranHons sorry for the late reply 🙏 when we say "night cycle" we are referring to when the population change and certain daily resource usages happen. The night cycle does not have a duration it is a quick event where we handle certain calculations.

I hope that helps 😊
